#!/usr/bin/env zsh

# Creates a new post

# -------------------------------- Functions -------------------------------- #

Err()
{
    printf "err: %s\n" "$2" 1>&2
    # shellcheck disable=2086
    (($1 > 0)) && exit $1
}

# ----------------------------- Input Processing ----------------------------- #

(($# == 0)) && Err 1 "Argument(s) required."

DocxFile="$1"

if [[ ${DocxFile##*.} != docx ]]; then
    Err 1 "$DocxFile is not a world document."
fi

# ----------------------------------- Main ----------------------------------- #

MdFile=${DocxFile%%.*}
MdFile=${MdFile,,}
MdFile=${MdFile// /-}
MdFile="./src/content/blog/$MdFile.md"

pandoc --extract-media ./public/ -t markdown_github -o "$MdFile" "$DocxFile" | sed "s/{.underline}//g"
