#!/usr/bin/env zsh

# Creates a new post

# Dependencies:
# date
# pandoc
# sed

# -------------------------------- Functions -------------------------------- #

Err()
{
    printf "err: %s\n" "$2" 1>&2
    # shellcheck disable=2086
    (($1 > 0)) && exit $1
}

# ----------------------------- Input Processing ----------------------------- #

(($# == 0)) && Err 1 "Argument(s) required."

DocxFile="$1"

if [[ ${DocxFile##*.} != docx ]]; then
    Err 1 "'$DocxFile' is not a world document."
fi

# ----------------------------------- Main ----------------------------------- #

MdFile=${DocxFile##*/}
MdFile=${MdFile%%.*}
MdFile=${MdFile:l} # to lowercase, zsh expecific
MdFile=${MdFile// /-}
MdFile="./src/content/blog/$MdFile.md"

pandoc --wrap none --extract-media ./public/ -t gfm -o "$MdFile" -- "$DocxFile"

Frontmatter="---\ntitle: '\1'\npubDate: '"$(date +'%b %d %Y')"'\nheroImage: '\\\'\ncategories: []\n---"
sed -i "s/^# \(.*\)/$Frontmatter/" -- "$MdFile"
