#!/usr/bin/env python3

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def err(code: int, msg: str) -> int:
    print(f"Err: {msg}", file=sys.stderr)
    return code


def main(args: list[str]) -> int:
    if len(args) == 1:
        return err(1, "Argument(s) required.")

    docx_file = Path(args[1])

    if docx_file.suffix != ".docx":
        return err(1, f"{docx_file.name} is not a world document.")

    md_file_contents = subprocess.check_output(
        [
            "pandoc",
            "--wrap", "none",
            "--extract-media", "./public/",
            "-t", "gfm",
            "--", docx_file,
        ],
    )
    md_file_name = docx_file.stem.lower().strip().replace("_", "").replace(" ", "-")
    md_file_path = f"./src/content/blog/{md_file_name}.md"

    with open(md_file_path, "w+", encoding="utf-8") as md_file:
        pattern = re.compile("^# (.+)")
        # FIXME: This breaks the moment a document doesn't have a title.
        # I should just replace the first heading on the document.
        substitution = pattern.sub(
            rf"""---
title: '\1'
pubDate: '{datetime.today().strftime("%b %d %Y")}'
heroImage: '\'
categories: []
---""",
            md_file_contents.decode("utf-8"),
        )

        md_file.write(substitution)

    # TODO: Format with prettier (`prettier --prose-wrap always -w`).

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
