[[communities]]
id = "Python Software Foundation"
role = "Directora"
years = "2023 - Actual"
url = "https://pyfound.blogspot.com/2023/06/announcing-2023-psf-board-election.html"
icon = "../images/communities/psf.png"
description = """
Organización sin fines de lucro dedicada a promover Python y su ecosistema de \
software libre y de código abierto en todo el mundo."""

[[communities]]
id = "PyCascades"
role = "Equipo de Organización"
years = "2022 - Actual"
url = "https://pycascades.com/"
icon = "../images/communities/PyCascades.png"
description = """
Conferencia regional en el noroeste del Pacífico que une a comunidades de \
Python de Vancouver, Seattle, Portland y Montreal."""

[[communities]]
id = "Python en Español"
role = "Equipo de Coordinación"
years = "2021 - Actual"
url = "https://hablemospython.dev/"
icon = "../images/communities/PythonEn Español.png"
description = """
Iniciativa que reúne a la comunidad hispanohablante para compartir recursos, \
conferencias, proyectos y actividades sobre Python."""

[[communities]]
id = "PyConUS Charlas"
role = "Co-Chair"
years = "2022 - Actual"
url = "https://us.pycon.org/2024/speaking/charlas/"
icon = "../images/communities/pycon charlas.jpeg"
description = """
Track de 2 días en PyCon US dedicado a charlas en español, destacando a \
Pythonistas hispanohablantes en la conferencia más grande de Python."""

[[communities]]
id = "Python Chile"
role = "Equipo de Coordinación"
years = "2021 - Actual"
url = "https://pythonchile.cl/"
icon = "../images/communities/Python Chile.png"
description = """
Comunidad que organiza conferencias y eventos educativos, buscando impactar el \
desarrollo de Python en Chile y a nivel mundial."""

[[communities]]
id = "PyLatam"
role = "Equipo de Organización"
years = "2020 - Actual"
url = "https://pylatam.org/"
icon = "../images/communities/PyLatam.png"
description = """
Conferencia latinoamericana que reúne a desarrolladores de Python de la región \
y fomenta la conexión con la comunidad global."""

[[communities]]
id = "PyLadies Santiago"
role = "Co-Organizadora"
years = "2021 - Actual"
url = "https://www.meetup.com/pyladies-santiago-de-chile/"
icon = "../images/communities/Pyladies Santiago Chile.png"
description = """
Capítulo en Santiago de Chile que promueve la participación de más mujeres en \
tecnología y programación con Python."""

[[communities]]
id = "PyLadies Santo Domingo"
role = "Co-Organizadora"
years = "2023 - Actual"
url = "https://www.meetup.com/pyladiessdq/"
icon = "../images/communities/PyLadies Santo Domingo.png"
description = """
Capítulo en Santo Domingo, RD, que fomenta la participación y el crecimiento \
de mujeres en la tecnología y el código con Python."""

[[communities]]
id = "PyLadies Montreal"
role = "Co-Organizadora"
years = "2023 - Actual"
url = "https://www.meetup.com/pyladiesmtl/"
icon = "../images/communities/PyLadies Montreal.jpg"
description = """
Capítulo internacional en Montreal que impulsa la inclusión de más mujeres en \
la comunidad de Python y la programación."""

[[communities]]
id = "PyLadiesCon"
role = "Equipo de Organización"
years = "2023 - Actual"
url = "https://conference.pyladies.com/"
icon = "../images/communities/PyLadiesCon.svg"
description = """
Conferencia global de PyLadies que empodera a mujeres y personas no binarias en \
Python con charlas, talleres y paneles inclusivos."""

[[communities]]
id = "Python Montreal"
role = "Equipo de voluntarios"
years = "2024 - Actual"
url = "https://montrealpython.org/"
icon = "../images/communities/Python Montreal.png"
description = """
Iniciativa que fomenta la comunidad Python en Montreal, promoviendo \
accesibilidad, aprendizaje y responsabilidad social."""

[[communities]]
id = "GitTogethers" 
role = "Community Leader" 
years = "2023 - Actual"
url = "https://github.com/gittogethers"
icon = "../images/communities/GitTogether.png"
description = """
Organización que impulsa eventos y colaboraciones en GitHub, reuniendo a \
desarrolladores y comunidades para aprender y crear."""

[[communities]]
id = "PyLadies En Español"
role = "Co-Organizadora"
years = "2022 - Actual"
url = "https://hablemospython.dev/pyladies.html"
icon = "../images/communities/Logo PyLadies en Español transparente.png"
description = """
Comunidad que empodera a mujeres en tecnología, impulsando capítulos en \
países hispanohablantes con apoyo, colaboración y recursos compartidos."""
