[[talks]]
id = "Colaborando con la Comunidad Python a través de la PSF"
place = "Python Brasil 2021"
date = "Oct 24 2021"
kind = "Conference"

[[talks]]
id = "Gestionando Comunidades Python: Creando y Manteniendo Espacios Colaborativos en Open Source"
place = "PyCon Panamá 2024"
date = "Oct 18 2024"
kind = "Conference"

[[talks]]
id = "Uniendo a las comunidades hispanohablantes de Python"
place = "PyConUS 2022"
date = "May 24 2022"
kind = "Conference"

[[talks]]
id = "PyCon Colombia - Organizing Snakes"
place = "PyCon Colombia 2024"
date = "Oct 07 2024"
kind = "Conference"

# Podcasts & Panels

[[talks]]
id = "Denny Perez on her journey into the Python Community"
place = "Sad Python Girls Club Podcast"
date = "Dec 06 2024"
kind = "Panel"

[[talks]]
id = "Denny Pérez: De contadora a coder, creando comunidades e inspirando mujeres"
place = "Free CodeCamp En Español Podcast"
date = "Jun 07 2024"
kind = "Panel"

[[talks]]
id = "Denny Perez: Desarrollé el liderazgo en las comunidades"
place = "BitaBit Podcast"
date = "Aug 29 2023"
kind = "Panel"

[[talks]]
id = "Lo mejor de Visual Studio Code Day 2022"
place = "Microsoft Reactor"
date = "Mar 16 2022"
kind = "Panel"

[[talks]]
id = "Panel PyLadies Chile"
place = "PyCon Chile 2023"
date = "Feb 03 2023"
kind = "Panel"

[[talks]]
id = "PyLadies: Conmemorando el dia de la Mujer"
place = "PyLadies Santiago Chile"
date = "Mar 25 2023"
kind = "Panel"

[[talks]]
id = "Python en Acción con Denny Perez"
place = "Charlas Tecnicas AWS Podcast"
date = "Nov 05 2024"
kind = "Panel"

[[talks]]
id = "Panel PyLadies: Un futuro acelerado: Igualdad de Genero e Inteligencia Artificial"
place = "PyCon Colombia 2024"
date = "Nov 25 2024"
kind = "Panel"

[[talks]]
id = "Community Organizers Summit"
place = "PyConUS 2024"
date = "May 18 2024"
kind = "Panel"

# Meetups & Interviews

[[talks]]
id = "Open Source con GitHub & Python: Oportunidades para Contribuir y Crecer en Comunidad"
place = "PyLadies Colombia"
date = "Oct 5 2024"
kind = "Meetup"

[[talks]]
id = "El poder de la comunidad en Python con Denny Pérez"
place = "Código Facilito"
date = "Mar 08 2023"
kind = "Meetup"

[[talks]]
id = "¿Cómo empezar con Python?"
place = "Dominicode"
date = "Oct 28 2020"
kind = "Meetup"

[[talks]]
id = "PyDev of the Week: Denny Perez"
place = "Mouse & Python by Mike"
date = "Jun 06 2022"
kind = "Meetup"

[[talks]]
id = "Python Day: Todo lo que necesitas saber para votar en las Elecciones de PSF"
place = "Python Nicaragua"
date = "May 27 2021"
kind = "Meetup"
